version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - "/.data/keycloak-postgres:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak_db
    ports:
      - "5435:5432"
    command: -p 5435
    #restart: unless-stopped
    networks:
      - keycloak-net

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: "postgres:5435"
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - "./.data/keycloak:/var/lib/keycloak/data"
      - "./config/keycloak/genappline-realm.json:/opt/jboss/keycloak/genappline-realm.json"
    ports:
      - "8484:8484"
    expose:
      - 8484
    command:
      - "-b 0.0.0.0"
      - "-Djboss.http.port=8484"
      - "-Dkeycloak.import=/opt/jboss/keycloak/genappline-realm.json"
    depends_on:
      - postgres
    networks:
      - keycloak-net

volumes:
  postgres:
  keycloak:

networks:
  keycloak-net:
    driver: bridge