version: '3.8'

services:

  gateway:
    build: ../gateway/.
    image: gateway
    container_name: gateway
    restart: on-failure
    ports:
      - 8090:8090
    expose:
      - "8090"
    environment:
      - APP_PORT=${APP_PORT}
      - TREE_DATA_SERVICE_ADDR=${TREE_DATA_SERVICE_ADDR}
      - KEYCLOAK_ADDR=${KEYCLOAK_ADDR}
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
    depends_on:
      - keycloak
    networks:
      - keycloak-net
      - opensearch-net

networks:
  keycloak-net:
    driver: bridge
  opensearch-net:
    driver: bridge
  monitoring: