scrape_configs:
  - job_name: 'gateway'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    scheme: http
    basic_auth:
      username: admin
      password: admin
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'gateway'
          instance: 'gateway-1'
  - job_name: 'tree-data'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'tree-data'
          instance: 'tree-data-1'